### ISSUE TITLE
propertius line 5 alignment problem

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#254]
reported by @monzug 

![text on side](https://user-images.githubusercontent.com/644870/62628819-03681b80-b8fa-11e9-99e4-7824fde3d3e8.JPG)

**Comment by balmas** [comment]
the alpheios edition was missing the line number on the 6th line, and comparing to the latest Perseus version in the PerseusDL/canonical-latinLit repo, it seems that all the line numbers in 1.2 were off by one. Fixed now.

**Comment by monzug** [comment]
the alignment is back, thanks. However I think we need to delete the extra nec (nec is repeated twice) on line 6  and also the non illis  on line 23 that is 'non n= illis' at the moment.

**Comment by balmas** [comment]
ok, will do.

**Comment by monzug** [comment]
Thanks, they are both gone.
I still see some inconsistencies with Scaife and Latin Library and Perseus.
in Scaife and Perseus and latin library, line 23,24, 25 we have 'tunc ego crediderim Manes et sidera vobis
posse Cytinaeis ducere carminibus.
aut'

in Alpheios, line 23, 24, 25  we have 'tunc ego crediderim vobis et sidera et amnis
posse Cytaeines ducere carminibus.
et'
with same editor Muller Lucian.
looking at the other editor Vincent Katz, Ed.   I can  see the same lines in Perseus and Alpheios. Maybe we have the wrong editor in bibliographic info, any idea?

**Comment by balmas** [comment]
I think our version is just very old, taken from Perseus back in 2008 or so and doesn't have all of the improvements and fixes that were made to the Perseus version incorporated.
